/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package edu.umn.d.cs1632;

import java.util.Properties;
import java.sql.Connection;
import java.sql.*;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 */
public class BaseballTeams extends javax.swing.JFrame {

    /**
     * Creates new form BaseballTeams
     */
    public BaseballTeams() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnGetTeamInfo = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblInfo = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        btnNext = new javax.swing.JButton();
        btnPrev = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnGetTeamInfo.setText("Get Team Info");
        btnGetTeamInfo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGetTeamInfoActionPerformed(evt);
            }
        });

        tblInfo.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        tblInfo.setToolTipText("");
        jScrollPane2.setViewportView(tblInfo);

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Baseball Info");

        btnNext.setText("Next 100");
        btnNext.setEnabled(false);
        btnNext.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNextActionPerformed(evt);
            }
        });

        btnPrev.setText("Prev 100");
        btnPrev.setEnabled(false);
        btnPrev.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPrevActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 542, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnGetTeamInfo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnPrev)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnNext))
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 390, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnNext)
                    .addComponent(btnGetTeamInfo)
                    .addComponent(btnPrev))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnGetTeamInfoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGetTeamInfoActionPerformed
        updateTable();
    }//GEN-LAST:event_btnGetTeamInfoActionPerformed

    private void btnNextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNextActionPerformed
        page++;
        updateTable();
    }//GEN-LAST:event_btnNextActionPerformed

    private void btnPrevActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPrevActionPerformed
        
        if (page > 0) {
            page--;
        }
        updateTable();
    }//GEN-LAST:event_btnPrevActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BaseballTeams.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BaseballTeams.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BaseballTeams.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BaseballTeams.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new BaseballTeams().setVisible(true);
            }
        });
    }
    
    public Connection getConnection() throws SQLException {
        if (username == null || password == null) {
            getUsernameAndPassword();
        }
        String url = "jdbc:postgresql://localhost:63333/";
        Properties props = new Properties();
        props.setProperty("user", username);
        props.setProperty("password", password);
        Connection conn = DriverManager.getConnection(url, props);
        return conn;
    }
    
    private void getUsernameAndPassword() {
        username = JOptionPane.showInputDialog("Enter DB username");
        password = PasswordDialog.showPasswordDialog();
    }
    
    private void updateTable() {
        boolean error = false;
        Connection conn = null;
        try  {
            conn = getConnection();
        } catch (SQLException s) {
            int ecode = s.getErrorCode();
            JOptionPane.showMessageDialog(rootPane, "Error: Could not connect to Database. Error "+Integer.toString(ecode), "Error", JOptionPane.WARNING_MESSAGE);
            username = null;
            password = null;
            error = true;
        }
        if (!error) {
            try {
                Statement stmt = conn.createStatement(ResultSet.TYPE_SCROLL_SENSITIVE, ResultSet.CONCUR_READ_ONLY);
//                String query = "SELECT * FROM BEAU0307.BASEBALLTEAMS WHERE ROWNUM <= 100";
                String query = "SELECT * FROM "
                        + "(SELECT teamid, name, park, ROW_NUMBER() over (order by franchid, yearid) FROM teams) as teams2 "
                        + "WHERE teams2.row_number > "+ (page*ROWS_PER_PAGE) +" AND teams2.row_number <= " + ((page+1)*ROWS_PER_PAGE);
                ResultSet rset = stmt.executeQuery(query);
                List<String> col_names = new ArrayList();
                col_names.add("Team ID");
                col_names.add("Team Name");
                col_names.add("Team Park");
                List<List<String>> data = new ArrayList();
                Integer count = 0;
                while (rset.next()) {
                    List<String> row = new ArrayList();
                    
                    row.add(rset.getString("teamid"));
                    row.add(rset.getString("name"));
                    row.add(rset.getString("park"));
                    data.add(row);
                    count++;
                }
                
                String[][] dataArray = data.stream().map(u -> u.toArray(new String[0])).toArray(String[][]::new);
                
                DefaultTableModel model = new DefaultTableModel(dataArray, col_names.toArray()) {
                    
                    @Override
                    public boolean isCellEditable(int row, int col) {
                        return false;
                    }
                    
                };
                
                tblInfo.setModel(model);
                if (page > 0) {
                    btnPrev.setEnabled(true);
                } else {
                    btnPrev.setEnabled(false);
                }
                if (count != ROWS_PER_PAGE) {
                    btnNext.setEnabled(false);
                } else {
                    btnNext.setEnabled(true);
                }
            } catch (SQLException s) {
                JOptionPane.showMessageDialog(rootPane, "Error: Could not execute sql query.", "Error", JOptionPane.WARNING_MESSAGE);
            }
        }
    }
    
    private String username = null;
    private String password = null;
    private Integer page = 0;
    private final Integer ROWS_PER_PAGE = 100;

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnGetTeamInfo;
    private javax.swing.JButton btnNext;
    private javax.swing.JButton btnPrev;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tblInfo;
    // End of variables declaration//GEN-END:variables
}
